package com.fujitsu.database.entity;

import com.fujitsu.base.entity.Page;
import com.google.gson.annotations.SerializedName;

public class WeChatUserInfo extends Page {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.open_id
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("openid")
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.subscribe
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("subscribe")
    private String subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.subscribe_time
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("subscribe_time")
    private String subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.nickname
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("nickname")
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.sex
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("sex")
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.country
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("country")
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.province
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("province")
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.city
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("city")
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.language
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("language")
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.head_img_url
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("headimgurl")
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.group_id
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("groupid")
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WECHAT_USER_INFO.remark
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @SerializedName("remark")
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.open_id
     *
     * @return the value of WECHAT_USER_INFO.open_id
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.open_id
     *
     * @param openId the value for WECHAT_USER_INFO.open_id
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.subscribe
     *
     * @return the value of WECHAT_USER_INFO.subscribe
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.subscribe
     *
     * @param subscribe the value for WECHAT_USER_INFO.subscribe
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setSubscribe(String subscribe) {
        this.subscribe = subscribe == null ? null : subscribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.subscribe_time
     *
     * @return the value of WECHAT_USER_INFO.subscribe_time
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.subscribe_time
     *
     * @param subscribeTime the value for WECHAT_USER_INFO.subscribe_time
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setSubscribeTime(String subscribeTime) {
        this.subscribeTime = subscribeTime == null ? null : subscribeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.nickname
     *
     * @return the value of WECHAT_USER_INFO.nickname
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.nickname
     *
     * @param nickname the value for WECHAT_USER_INFO.nickname
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.sex
     *
     * @return the value of WECHAT_USER_INFO.sex
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.sex
     *
     * @param sex the value for WECHAT_USER_INFO.sex
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.country
     *
     * @return the value of WECHAT_USER_INFO.country
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.country
     *
     * @param country the value for WECHAT_USER_INFO.country
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.province
     *
     * @return the value of WECHAT_USER_INFO.province
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.province
     *
     * @param province the value for WECHAT_USER_INFO.province
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.city
     *
     * @return the value of WECHAT_USER_INFO.city
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.city
     *
     * @param city the value for WECHAT_USER_INFO.city
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.language
     *
     * @return the value of WECHAT_USER_INFO.language
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.language
     *
     * @param language the value for WECHAT_USER_INFO.language
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.head_img_url
     *
     * @return the value of WECHAT_USER_INFO.head_img_url
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.head_img_url
     *
     * @param headImgUrl the value for WECHAT_USER_INFO.head_img_url
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.group_id
     *
     * @return the value of WECHAT_USER_INFO.group_id
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.group_id
     *
     * @param groupId the value for WECHAT_USER_INFO.group_id
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WECHAT_USER_INFO.remark
     *
     * @return the value of WECHAT_USER_INFO.remark
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WECHAT_USER_INFO.remark
     *
     * @param remark the value for WECHAT_USER_INFO.remark
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WeChatUserInfo other = (WeChatUserInfo) that;
        return (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
                && (this.getSubscribe() == null ? other.getSubscribe() == null : this.getSubscribe().equals(other.getSubscribe()))
                && (this.getSubscribeTime() == null ? other.getSubscribeTime() == null : this.getSubscribeTime().equals(other.getSubscribeTime()))
                && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
                && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
                && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
                && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
                && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
                && (this.getLanguage() == null ? other.getLanguage() == null : this.getLanguage().equals(other.getLanguage()))
                && (this.getHeadImgUrl() == null ? other.getHeadImgUrl() == null : this.getHeadImgUrl().equals(other.getHeadImgUrl()))
                && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getSubscribe() == null) ? 0 : getSubscribe().hashCode());
        result = prime * result + ((getSubscribeTime() == null) ? 0 : getSubscribeTime().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getLanguage() == null) ? 0 : getLanguage().hashCode());
        result = prime * result + ((getHeadImgUrl() == null) ? 0 : getHeadImgUrl().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", openId=").append(openId);
        sb.append(", subscribe=").append(subscribe);
        sb.append(", subscribeTime=").append(subscribeTime);
        sb.append(", nickname=").append(nickname);
        sb.append(", sex=").append(sex);
        sb.append(", country=").append(country);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", language=").append(language);
        sb.append(", headImgUrl=").append(headImgUrl);
        sb.append(", groupId=").append(groupId);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}