package com.fujitsu.database.mapper;

import com.fujitsu.database.entity.WeChatUserInfo;
import com.fujitsu.database.entity.WeChatUserInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WeChatUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int countByExample(WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int deleteByExample(WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int insert(WeChatUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int insertSelective(WeChatUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    List<WeChatUserInfo> selectByExampleWithBLOBs(WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    List<WeChatUserInfo> selectByExample(WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") WeChatUserInfo record, @Param("example") WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") WeChatUserInfo record, @Param("example") WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WECHAT_USER_INFO
     *
     * @mbggenerated Thu Jul 14 19:38:58 CST 2016
     */
    int updateByExample(@Param("record") WeChatUserInfo record, @Param("example") WeChatUserInfoExample example);
}